name: Send Webhook Event

on:
  push:
  pull_request:
    types: [opened, closed, synchronize]

jobs:
  send-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Send webhook for push/pull/merge
        run: |
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

          curl -X POST https://web-production-7583.up.railway.app/webhook \
            -H "Content-Type: application/json" \
            -d '{
              "event": "${{ github.event_name }}",
              "action": "${{ github.event.action }}",
              "timestamp": "'$TIMESTAMP'",
              "repository": "${{ github.repository }}",
              "sender": "${{ github.actor }}",
              "ref": "${{ github.ref }}",
              "base_ref": "${{ github.event.pull_request.base.ref }}",
              "head_ref": "${{ github.event.pull_request.head.ref }}"
            }'
